// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.example;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string username = 2;</code>
   */
  String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
