// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userservice.proto

package com.example;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
